openapi: 3.1.0
info:
  title: ChatKit Message Runs API
  version: 1.0.0
  description: Send messages and receive streaming AI responses

servers:
  - url: http://localhost:8000/api/v1

security:
  - BearerAuth: []

paths:
  /chatkit/sessions/{session_id}/threads/{thread_id}/runs:
    post:
      summary: Send message and stream AI response
      description: |
        Sends a user message to the AI assistant and streams the response via Server-Sent Events (SSE).
        Translates REST request to ChatKit JSON-RPC `threads.add_user_message` protocol.

        **Response Format**: `text/event-stream` (Server-Sent Events)
        **Tool Calls**: Assistant may invoke tools (add_task, list_tasks, etc.)
      operationId: sendMessage
      tags:
        - Runs
      security:
        - BearerAuth: []
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: thread_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [message]
              properties:
                message:
                  type: object
                  required: [role, content]
                  properties:
                    role:
                      type: string
                      enum: [user]
                    content:
                      type: array
                      items:
                        type: object
                        required: [type, text]
                        properties:
                          type:
                            type: string
                            enum: [input_text]
                          text:
                            type: string
                            minLength: 1
                            maxLength: 10000
            example:
              message:
                role: "user"
                content:
                  - type: "input_text"
                    text: "Add task: Buy milk"
      responses:
        '200':
          description: SSE streaming response
          content:
            text/event-stream:
              schema:
                type: string
                description: Server-Sent Events stream
              examples:
                streaming_response:
                  summary: Example SSE stream
                  value: |
                    data: {"type": "response.chunk", "content": "I'll"}

                    data: {"type": "response.chunk", "content": " add"}

                    data: {"type": "response.done", "finish_reason": "stop"}

        '400':
          description: Bad Request (validation error)
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Session or thread not found
        '429':
          description: Rate limit exceeded (max 30 req/min)
        '502':
          description: Bad Gateway (OpenRouter API error)

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
