openapi: 3.1.0
info:
  title: ChatKit Threads API
  version: 1.0.0
  description: Thread management endpoints (implicit - threads map 1:1 to sessions)

servers:
  - url: http://localhost:8000/api/v1

security:
  - BearerAuth: []

paths:
  /chatkit/sessions/{session_id}/threads:
    post:
      summary: Create thread in session
      description: |
        Creates a thread within a session. In ChatKit data model, each session has exactly one thread.
        This endpoint is idempotent - returns existing thread if already created.
      operationId: createThread
      tags:
        - Threads
      security:
        - BearerAuth: []
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: Thread created successfully
          content:
            application/json:
              schema:
                type: object
                required: [success, data]
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    required: [id, session_id, created_at]
                    properties:
                      id:
                        type: string
                        format: uuid
                        description: Thread ID (same as session ID)
                      session_id:
                        type: string
                        format: uuid
                      created_at:
                        type: string
                        format: date-time
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (user doesn't own session)
        '404':
          description: Session not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
